# Site settings
title: Stepping Sideways
email: john.woods@gobaci.com
description: > # this means to ignore newlines until "baseurl:"
  Stepping Sideways is a deck of cards designed to help us break
  out of mental habits and physical routines - habits and routines 
  which may be invisible to us and which may reinforce our isolation 
  and stuck-ness.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.steppingsideways.com" # the base hostname & protocol for your site
gitstatic: "https://github.com/steppingsideways/steppingsideways.github.io/blob/master/"
twitter_username: gobaci 
github_username: burnabyassociation

# Build settings
markdown: kramdown
